PATHTOROOT = ../openfx/Support

include $(PATHTOROOT)/Plugins/Makefile.master

CXXFLAGS += -DOFX_EXTENSIONS_VEGAS -DOFX_EXTENSIONS_NUKE -DOFX_EXTENSIONS_NATRON -DOFX_EXTENSIONS_TUTTLE -DOFX_SUPPORTS_OPENGLRENDER

CXXFLAGS += -I../OpenCV -I../SupportExt
CXXFLAGS += $(shell pkg-config opencv --cflags)
LINKFLAGS += $(shell pkg-config opencv --libs)
VPATH += ../OpenCV ../SupportExt
