PLUGINOBJECTS = Deflicker.o
PLUGINNAME = Deflicker
#RESOURCES = net.sf.openfx.VectorGenerator.png net.sf.openfx.VectorGenerator.svg


TOP_SRCDIR = ..

VPATH += \
$(TOP_SRCDIR)/Deflicker

include $(TOP_SRCDIR)/Makefile.master