PLUGINOBJECTS = ShotCutDetection.o ofxsLut.o ofxsRectangleInteract.o
PLUGINNAME = ShotCutDetection
RESOURCES = net.sf.openfx.ShotCutDetection.png

TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.master
