PLUGINOBJECTS = RemoveScratches.o  Scratches.o ofxsRectangleInteract.o
PLUGINNAME = RemoveScratches
RESOURCES = net.sf.openfx.RemoveScratches.png


TOP_SRCDIR = ..

VPATH += \
$(TOP_SRCDIR)/RemoveScratches

include $(TOP_SRCDIR)/Makefile.master
