PLUGINOBJECTS = RemoveScratches.o  Scratches.o ofxsRectangleInteract.o
PLUGINNAME = RemoveScratches
#RESOURCES = net.sf.openfx.VectorGenerator.png net.sf.openfx.VectorGenerator.svg


TOP_SRCDIR = ..

VPATH += \
$(TOP_SRCDIR)/RemoveScratches

include $(TOP_SRCDIR)/Makefile.master
